# CI de Nivel 01 - Disparo manual a partire de um clique

name: 'Execucao Agendada'

on:
  schedule:
    - cron: '7 18 * * 0'

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Teste E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report