# CI de Nivel 03 - Disparo sempre que deply executado

name: 'Execucao por Deploy'

on:
  workflow_run: ['Execucao Manual']
  types:
    - completed

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Teste E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report