# CI de Nivel 04 - Disparo dentro do fluxo de CI de desenvolvimento

name: 'Execucao Integrada'

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Padronizacao de codigo (Lint)
        run: yarn lint

  units:
    runs-on: ['ubuntu-latest']
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Testes de unidade
        run: yarn run test

  e2e-tests:
    runs-on: ['ubuntu-latest']
    needs: [units]
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicacao local
        run: yarn start &

      - name: Teste E2E
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

  deploy:
    runs-on: ['ubuntu-latest']
    needs: [e2e-tests]

    steps:
      - name: Deploy
        run: echo "step deploy"
